name       : python-notify2
version    : 0.3
release    : 3
source     :
    - https://pypi.python.org/packages/7f/be/f749b44ac10ca9e4b9e54a9549e37233b30451bd1c12ece640bec730c0e5/notify2-0.3.tar.gz : 684281f91c51fc60bc7909a35bd21d043a2a421f4e269de1ed1f13845d1d6321
license    : BSD-2-Clause
component  : programming.python
summary    : notify2 is a replacement for pynotify
description: |
    notify2 is a replacement for pynotify which can be used from different GUI toolkits and from programs without a GUI.
    The API is largely the same as that of pynotify, but some less important parts are left out.
builddeps  :
    - pkgconfig(python3)
    - python3-dbus
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
